### ISSUE TITLE
external-ip of `usersvc` stuck in pending state

### ISSUE THREAD

**Issue by kelvinji2009** [datawire/envoy-steps#2]
I am just using the virtualbox driver for minikube.

★  envoy-steps git:(master) ⚡️  »kubectl get service
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
kubernetes   10.0.0.1     <none>        443/TCP          44m
postgres     10.0.0.121   <none>        5432/TCP         9m
usersvc      10.0.0.11    <pending>     5000:31712/TCP   9m

★  envoy-steps git:(master) ⚡️  »kubectl describe services
Name:			kubernetes
Namespace:		default
Labels:			component=apiserver
			provider=kubernetes
Annotations:		<none>
Selector:		<none>
Type:			ClusterIP
IP:			10.0.0.1
Port:			https	443/TCP
Endpoints:		10.0.2.15:8443
Session Affinity:	ClientIP
Events:			<none>

Name:			postgres
Namespace:		default
Labels:			service=postgres
Annotations:		<none>
Selector:		service=postgres
Type:			ClusterIP
IP:			10.0.0.121
Port:			postgres	5432/TCP
Endpoints:		172.17.0.4:5432
Session Affinity:	None
Events:			<none>

Name:			usersvc
Namespace:		default
Labels:			service=usersvc
Annotations:		<none>
Selector:		service=usersvc
Type:			LoadBalancer
IP:			10.0.0.11
Port:			usersvc	5000/TCP
NodePort:		usersvc	31712/TCP
Endpoints:		172.17.0.5:5000
Session Affinity:	None
Events:			<none>

**Comment by kelvinji2009** [comment]
I got the same issue after trying `minikube start --vm-driver xhyve`

**Comment by kelvinji2009** [comment]
Maybe it is not a big deal. Everything works fine as your description. Sorry.

**Comment by ark3** [comment]
Minikube does not support external IPs in that manner. That's why you must use `minikube service --url usersvc`to get the target address.

**Comment by kelvinji2009** [comment]
@ark3 Yep. Thanks a lot.

**Comment by m1ch0pv** [comment]
Created a new issue with this for better visibility: https://github.com/datawire/envoy-steps/issues/5


I'm having the same issue at step 3: _edge-envoy_ external IP is stuck in `pending` status and in my case every time I try to interact with edge-envoy API  I get `no healthy upstream`.

NAME                              READY   STATUS    RESTARTS   AGE
pod/edge-envoy-765798cf45-sw2q5   1/1     Running   2          6m
pod/postgres-6ccf94dfb7-kpsnp     1/1     Running   1          2h
pod/usersvc-645d6877fb-rx55n      1/1     Running   0          6m
pod/usersvc-sds-f777d75c5-xs7tf   1/1     Running   0          6m

NAME                  TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/edge-envoy    LoadBalancer   10.109.35.117    <pending>     8000:32149/TCP   6m
service/kubernetes    ClusterIP      10.96.0.1        <none>        443/TCP          39d
service/postgres      ClusterIP      10.96.245.172    <none>        5432/TCP         2h
service/usersvc       ClusterIP      10.100.132.170   <none>        80/TCP           6m
service/usersvc-sds   NodePort       10.98.212.241    <none>        5000:31085/TCP   6m

I'm using macOS High Sierra (10.13.6)

**minikube** version: v0.30.0

**kubectl** version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**docker** version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.35
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          17.12.1-ce
  API version:      1.35 (minimum version 1.12)
  Go version:       go1.9.4
  Git commit:       7390fc6
  Built:            Tue Feb 27 22:20:43 2018
  OS/Arch:          linux/amd64
  Experimental:     false


Thanks
